// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/services/jwt.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	commands "sso-service/internal/domain/dto/jwt/commands"
	results "sso-service/internal/domain/dto/jwt/results"

	gomock "github.com/golang/mock/gomock"
)

// MockJWT is a mock of JWT interface.
type MockJWT struct {
	ctrl     *gomock.Controller
	recorder *MockJWTMockRecorder
}

// MockJWTMockRecorder is the mock recorder for MockJWT.
type MockJWTMockRecorder struct {
	mock *MockJWT
}

// NewMockJWT creates a new mock instance.
func NewMockJWT(ctrl *gomock.Controller) *MockJWT {
	mock := &MockJWT{ctrl: ctrl}
	mock.recorder = &MockJWTMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWT) EXPECT() *MockJWTMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockJWT) Generate(command commands.Generate) (*results.Generate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", command)
	ret0, _ := ret[0].(*results.Generate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockJWTMockRecorder) Generate(command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockJWT)(nil).Generate), command)
}

// Parse mocks base method.
func (m *MockJWT) Parse(command commands.Parse) (*results.Parse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Parse", command)
	ret0, _ := ret[0].(*results.Parse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse.
func (mr *MockJWTMockRecorder) Parse(command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockJWT)(nil).Parse), command)
}
