// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/repositories/token.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	"sso-service/internal/domain/dto/tokens/commands"
	"sso-service/internal/domain/dto/tokens/results"
	tx "sso-service/internal/domain/interfaces/tx"

	gomock "github.com/golang/mock/gomock"
)

// MockRefreshToken is a mock of RefreshToken interface.
type MockRefreshToken struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshTokenMockRecorder
}

// MockRefreshTokenMockRecorder is the mock recorder for MockRefreshToken.
type MockRefreshTokenMockRecorder struct {
	mock *MockRefreshToken
}

// NewMockRefreshToken creates a new mock instance.
func NewMockRefreshToken(ctrl *gomock.Controller) *MockRefreshToken {
	mock := &MockRefreshToken{ctrl: ctrl}
	mock.recorder = &MockRefreshTokenMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshToken) EXPECT() *MockRefreshTokenMockRecorder {
	return m.recorder
}

// AddTx mocks base method.
func (m *MockRefreshToken) AddTx(ctx context.Context, tx tx.Tx, command commands.Add) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTx", ctx, tx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTx indicates an expected call of AddTx.
func (mr *MockRefreshTokenMockRecorder) AddTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTx", reflect.TypeOf((*MockRefreshToken)(nil).AddTx), ctx, tx, command)
}

// BeginTx mocks base method.
func (m *MockRefreshToken) BeginTx(ctx context.Context) (tx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(tx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockRefreshTokenMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockRefreshToken)(nil).BeginTx), ctx)
}

// UpdateByTokenTx mocks base method.
func (m *MockRefreshToken) UpdateByTokenTx(ctx context.Context, tx tx.Tx, command commands.UpdateByToken) (*results.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByTokenTx", ctx, tx, command)
	ret0, _ := ret[0].(*results.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByTokenTx indicates an expected call of UpdateByTokenTx.
func (mr *MockRefreshTokenMockRecorder) UpdateByTokenTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByTokenTx", reflect.TypeOf((*MockRefreshToken)(nil).UpdateByTokenTx), ctx, tx, command)
}

// UpdateByUserIDTx mocks base method.
func (m *MockRefreshToken) UpdateByUserIDTx(ctx context.Context, tx tx.Tx, command commands.UpdateByUserID) (*results.Update, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByUserIDTx", ctx, tx, command)
	ret0, _ := ret[0].(*results.Update)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateByUserIDTx indicates an expected call of UpdateByUserIDTx.
func (mr *MockRefreshTokenMockRecorder) UpdateByUserIDTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByUserIDTx", reflect.TypeOf((*MockRefreshToken)(nil).UpdateByUserIDTx), ctx, tx, command)
}
