// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/repositories/user.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	commands "sso-service/internal/domain/dto/user/commands"
	results "sso-service/internal/domain/dto/user/results"
	tx "sso-service/internal/domain/interfaces/tx"

	gomock "github.com/golang/mock/gomock"
)

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// AddTx mocks base method.
func (m *MockUser) AddTx(ctx context.Context, tx tx.Tx, command commands.Add) (*results.Add, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTx", ctx, tx, command)
	ret0, _ := ret[0].(*results.Add)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddTx indicates an expected call of AddTx.
func (mr *MockUserMockRecorder) AddTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTx", reflect.TypeOf((*MockUser)(nil).AddTx), ctx, tx, command)
}

// BeginTx mocks base method.
func (m *MockUser) BeginTx(ctx context.Context) (tx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(tx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockUserMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockUser)(nil).BeginTx), ctx)
}

// GetByID mocks base method.
func (m *MockUser) GetByID(ctx context.Context, userID int64) (*results.Get, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID)
	ret0, _ := ret[0].(*results.Get)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserMockRecorder) GetByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUser)(nil).GetByID), ctx, userID)
}

// GetByLogin mocks base method.
func (m *MockUser) GetByLogin(ctx context.Context, command commands.GetByLogin) (*results.Get, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLogin", ctx, command)
	ret0, _ := ret[0].(*results.Get)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLogin indicates an expected call of GetByLogin.
func (mr *MockUserMockRecorder) GetByLogin(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLogin", reflect.TypeOf((*MockUser)(nil).GetByLogin), ctx, command)
}
